

```{r}

if(!require("gbm")){
  install.packages("gbm")
}

library(gbm)
library(adabag)
library(data.table)
library(dplyr)
library(randomForest)
library(parallel)
library(e1071)
source("../lib/cross_validation.R")
source("../lib/train.R")
source("../lib/test.R")
```



```{r}
sift <- data.frame(t(read.csv("../data/sift_features.csv")))
y<-c(rep(0,1000),rep(1,1000))
s1<-data.frame(cbind(y,sift))
pca <- data.frame(read.csv("../output/feature_pca.csv"))
lasso<- data.frame(read.csv("../output/feature_lasso.csv"))
hog1<- data.frame(read.csv("../output/hog1.csv"))
hog1<- hog1[,-1]
lasso<-lasso[,-1]
pca<-pca[,-1]
num<-apply(abs(sign(sift)),1,sum)
```





gbm!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```{r warning=FALSE}
k<-3
cl <- makeCluster(getOption("cl.cores", 8))
err<-parLapply(cl, 1:16, cv.function,X.train=sift, y.train=y, K=k)
plot(err)
d<-which.min(err)
gbmbase <- gbm.fit(x=sift, y=y,
                     n.trees=1000,
                     distribution="bernoulli",
                     interaction.depth=d, 
                     bag.fraction = 0.5,
                     verbose=FALSE)
save(gbmbase,file="Basicmodel.RData")
```




feature

```{r}
load("../output/feature0.Rdata")
feature0<-unlist(feature0)

feature<-cbind(num,feature0,hog1)
save(feature,file="feature.RData")
```






random forest!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


```{r}

t1<-Sys.time()
cl <- makeCluster(getOption("cl.cores", 8))
rderr1 <- parLapply(cl, 1:8,  rf.cv.function,X.train=feature, y.train=y,ntree=1000, K=k)
rderr1<-unlist(rderr1)
plot(rderr1)
t2<-Sys.time()
t2-t1
```




```{r}
rf_fit <- randomForest(x=feature,y=as.factor(y),
                         importance=TRUE, 
                         ntree=1000,
                         nodesize=3)
save(rf_fit,file="Advancemodel.RData")
```


```{r}
pred<-rf_test(rf_fit,feature)
mean(pred==y)
```

